# docker-compose.yml (в корне)
version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: task_manager_dev
    ports: [ "5432:5432" ]
    restart: unless-stopped
